//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LM_GsbE5CsharpEntities : DbContext
    {
        public LM_GsbE5CsharpEntities()
            : base("name=LM_GsbE5CsharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<composant> composant { get; set; }
        public DbSet<constituer> constituer { get; set; }
        public DbSet<famille> famille { get; set; }
        public DbSet<medicament> medicament { get; set; }
        public DbSet<offrir> offrir { get; set; }
        public DbSet<praticien> praticien { get; set; }
        public DbSet<rapport_visite> rapport_visite { get; set; }
        public DbSet<type_praticien> type_praticien { get; set; }
        public DbSet<visiteur> visiteur { get; set; }
    }
}
